default_install_hook_types: [pre-commit, post-checkout, post-merge, post-rewrite]
repos:
  - repo: https://github.com/jmelahman/config-init
    rev: v0.1.1
    hooks:
      - id: config-init
  - repo: local
    hooks:
      - id: check
        name: build and test with both toolchains
        entry: make check
        language: system
        files: '(\.go|\.mod|\.sum)$'
        pass_filenames: false
