// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so", os.Args, []testing.Test{
		{Name: "TestInitNoConfigDir", F: TestInitNoConfigDir},
		{Name: "TestInitCreatesAndRepairsLinks", F: TestInitCreatesAndRepairsLinks},
		{Name: "TestInitConflict", F: TestInitConflict},
		{Name: "TestNotARepo", F: TestNotARepo},
		{Name: "TestPreCommitInsertExisting", F: TestPreCommitInsertExisting},
		{Name: "TestMigrateBasic", F: TestMigrateBasic},
		{Name: "TestMigrateIdempotent", F: TestMigrateIdempotent},
		{Name: "TestMigrateExplicit", F: TestMigrateExplicit},
		{Name: "TestMigrateSkipsDefaults", F: TestMigrateSkipsDefaults},
		{Name: "TestMigrateDryRun", F: TestMigrateDryRun},
		{Name: "TestGitignoreCompanionPatterns", F: TestGitignoreCompanionPatterns},
		{Name: "TestMigrateConflict", F: TestMigrateConflict},
	})
}
